/*
 * Generated by MTK Easy PinMux Tool Version 2.5.8 for 7698. Copyright MediaTek Inc. (C) 2015.
 * 2019-02-19 15:43:35:0234
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
